### PR TITLE
Search by topic

### PR DESCRIPTION
**Pull request by ghost**
To go with the new tags.md.

### CODE REVIEW

**Comment by isRuslan** [comment]
@willnwhite can you please create one pull request for all tags.md work. This PR will be in continuation state and will be merged after all tags-related work will finished.

**Comment by ghost** [comment]
Sure, though won't that delay tags getting into the public tags.md? And won't keeping this PR open delay others using and contributing to tags.md?

**Comment by isRuslan** [comment]
In our case is ok to delay pushing tags.md to get a complete file.

**Comment by sporto** [comment]
This tags.md only has two entries. Which is not really useful. I'm deleting this for now.

**Pull request closed without merging**
