### PR TITLE
Problem: Potentially confusing reference to QML

### PR DESCRIPTION
**Pull request by julianpistorius**
Background:

PR #134 from @ShalokShalom introduced a link to QML with the idea that one could make mobile and desktop applications with Elm. QML is very cool, and I really want this to be true, but unfortunately there seems to be no real-world example (I searched!)

There was a similar PR to Fable by same author who admits that it is currently only a hypothetical possibility:

https://github.com/fable-compiler/fable-compiler.github.io/issues/14#issuecomment-335104505

In the absence of a concrete example of using QML with Elm this link to QML is just going to confuse and distract people.

I propose removing this link.

### CODE REVIEW

**Comment by ShalokShalom** [comment]
Yes, this is theoretical. QML can import JS files, so I dont see why it should not work?

**Comment by julianpistorius** [comment]
> Yes, this is theoretical. QML can import JS files, so I dont see why it should not work?

Thanks @ShalokShalom! Yes I independently came to the same conclusion as you - that it might be possible _in theory_. When I searched if anybody had done this I came across your PR, but sadly no example of this in practice. I hope this PR encourages somebody to come forward with an actual example.

**Comment by ShalokShalom** [comment]
You mean nobody has ever imported JS files? The output from Fable and Elm is no different from handwritten code. Not in a way that it gets incompatible at least. 

I can imagine that some adjustments have to be done in order to wire them together, can you say something about that?

Thanks :+1:

**Comment by julianpistorius** [comment]
Good question. I'll try to answer this in three parts.

1. Elm is not just a way to generate JavaScript. I'd say its most distinguishing feature is The Elm Architecture (TEA) programming model. It's also sometimes called Model View Update. When I say I want to see Elm integration with QML, I really mean I'd like to see an idiomatically 'Elmish' way to generate desktop/mobile applications using The Elm Architecture with QT for widgets. Would we have to figure out how to make Elm generate QML as a pure Elm view function? Or something else? I don't know enough about either Elm or QT, but I think this might require more work than 'just generate some JavaScript'.

2. The other great thing about Elm is the static type system. Given that QT is written in C++ I would love to see Elm being able to interact with QT objects in a type-safe way. But I wouldn't even know where to start.

3. Elm has a very distinct, constrained, and opinionated way of integrating with JavaScript and with external services which can have side-effects (web services, etc.). Instead of calling JavaScript functions directly it uses ports - and treats JavaScript like an external service, using message-passing (kinda like the Actor Model). I have no idea how this would work with something like QML - where there isn't a browser. How would it interact with the non-Elm parts of the QT application, and with operating system features which can have side-effects?

As Fox Mulder says: "I want to believe!" - but sadly I haven't seen anything that makes me think this is as simple as using Elm to generate some JavaScript.

Does that make sense?

**Comment by ShalokShalom** [comment]
Sure. 

1) Completely true, while having a way to code in the prefered language is always nice.  
2) Great optional addition. No project starts at 100 % coverage. 
3) Yep, can be an issue. You can do that with Elchemy?

**Comment by julianpistorius** [comment]
Hi @ShalokShalom,

I had a another look at both QML and Elchemy to make sure I wasn't missing anything. I also had a look at a couple of projects which call out to Elm in non-standard ways:

- https://github.com/ktonon/elm-serverless
- https://github.com/jfairbank/run-elm

Both these two projects had to do considerable work and build quite a bit of scaffolding to work with Elm over a very restricted interface.

Elchemy's author recommends not doing anything in Elchemy that has side-effects: https://github.com/wende/elchemy/issues/297

I'll keep my eyes open for ways to make this a reality, and I will be very happy when this happens, but until then I don't think this link is useful to the wider Elm community.

It is up to the maintainers of the repo to merge this PR. If nothing else this thread will be useful to future travelers. (Hello you lucky people from the future who can write native desktop & mobile applications in Elm! How I envy you! 😆)

Thanks for the thoughtful discussion @ShalokShalom, and may you build many cool things. 👋

**Comment by ShalokShalom** [comment]
> (Hello you lucky people from the future who can write native desktop & mobile applications in Elm! How I envy you! :laughing:)

You can now use [Fabulous](https://github.com/fsprojects/Fabulous) and [Bolero](https://fsbolero.io) in order to build Elm like applications. 

There are also other solutions, all based on the Elm Archticture implementation [Elmish](https://github.com/elmish/elmish)

**Comment by julianpistorius** [comment]
> You can now use [Fabulous](https://github.com/fsprojects/Fabulous) and [Bolero](https://fsbolero.io) in order to build Elm like applications.
> 
> There are also other solutions, all based on the Elm Archticture implementation [Elmish](https://github.com/elmish/elmish)

Very cool! Thanks for heads-up.

**Comment by sporto** [comment]
I have removed the QML link for now, as it sends you to a page without little relevance for Elm.
I added a link to Fabulous as it seems relevant.

**Comment by ShalokShalom** [comment]
And Bolero?

It is Elmish for WebAssembly and Elmish is Elm for FSharp. 

https://fsbolero.io/docs/Elmish

**Comment by sporto** [comment]
Added, thanks

**Pull request closed without merging**
