### PR TITLE
Update logo src

### PR DESCRIPTION
**Pull request by lesykos**

### CODE REVIEW

**Comment by isRuslan** [comment]
Is it a new language logo? I don't think so.

**Comment by decentral1se** [comment]
It appears to be ... ? Strange ...

It is there on the home page: http://elm-lang.org/

**Comment by isRuslan** [comment]
I think it is just a web front design, relative github organization still use  https://github.com/elm-lang
Thanks for your efforts @Lesuk @lwm but I prefer keep the current one 👍

**Comment by lesykos** [comment]
@isRuslan yes, of course, colored version of logo is best, I just updated the source of image from official site, because old source is removed.

**Comment by isRuslan** [comment]
@Lesuk oh I see, thanks for fixes!

**Pull request merged**
