### PR TITLE
Add elm-http-extra

### PR DESCRIPTION
**Pull request by lukewestby**
Just wanted to throw my own elm-http-extra in if you'll take it :smiley:

The design for the API came out of a discussion in the Slack channel, and we've got positive feedback from those that use it! I'm hoping more folks will adopt it and help improve it.

### CODE REVIEW

**Comment by isRuslan** [comment]
Thanks for contributing, it is looking promising :+1: 
But you have made a typo in link url, can you fix it and squash commits?

**Comment by lukewestby** [comment]
Sure, will do. Thanks!

**Comment by lukewestby** [comment]
all set!

**Comment by isRuslan** [comment]
Thanks, added!

**Pull request merged**
