### PR TITLE
Add elm cheat sheet in Learn section

### PR DESCRIPTION
**Pull request by izdi**
Hi, 
I'm making a cheat sheet for Elm, this is still in progress, I'm planning on finishing this week.

### CODE REVIEW

**Comment by isRuslan** [comment]
Hi, ping me here when you'll finished this sheet.

**Comment by izdi** [comment]
@isRuslan Hey, I think you could add it since almost all of my work is done and it's been seen by internet.

**Comment by isRuslan** [comment]
Yeah, this is really helpful :+1: Thanks!

I'll merge this manually, because of the conflicts.

**Comment by izdi** [comment]
Thanks!

**Pull request closed without merging**
